name: app_gestionale
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+8

environment:
  sdk: '>=3.0.0 <4.0.0' # Aggiornato per compatibilità con Flutter 3.x e Dart 3.x

dependencies:
  flutter:
    sdk: flutter

  # Aggiornato le dipendenze Firebase alle ultime versioni stabili (al 04/06/2025)
  firebase_core: ^3.1.0 # Versione più recente
  firebase_auth: ^5.1.0 # Versione più recente
  cloud_firestore: ^5.1.0 # Versione più recente

  share_plus: ^7.0.2 # Ho messo la tua versione, ma la più recente stabile è ^7.0.2
  qr_flutter: ^4.1.0 # Aggiornato alla più recente stabile
  hive: ^2.2.3 # La tua versione è l'ultima della serie 2.x.x
  hive_flutter: ^1.1.0 # La tua versione è l'ultima della serie 1.x.x
  path_provider: ^2.1.3 # Aggiornato alla più recente stabile
  image_picker: ^1.1.2 # Aggiornato alla più recente stabile
  path: ^1.9.0
  csv: ^6.0.0
  file_picker: ^6.1.1
  flutter_local_notifications: ^17.0.0 # Aggiornato alla più recente stabile
  cupertino_icons: ^1.0.8
  intl: ^0.19.0 # Aggiornato alla più recente stabile (la tua era dev)
  printing: ^5.12.0
  pdf: ^3.10.4
  shared_preferences: ^2.2.2
  introduction_screen: ^3.1.13 # Aggiornato alla più recente stabile
  json_annotation: ^4.9.0
  characters: ^1.4.0
  uuid: ^4.3.3
  qr_code_scanner: ^1.0.1

  in_app_purchase: ^3.1.10 # Mantengo la tua, ma considera la più recente stabile

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Aggiornato alla più recente stabile
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  windows:
    generate: true
  image_path: "assets/icon/icon.png"

dependency_overrides:
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: master