// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNBP3EfhLsnnz5OcQsPg2EpnQE19qvKG4',
    appId: '1:214242900706:web:cfca2c3098dd28a54ffcbb',
    messagingSenderId: '214242900706',
    projectId: 'stand-app-fce12',
    authDomain: 'stand-app-fce12.firebaseapp.com',
    storageBucket: 'stand-app-fce12.firebasestorage.app',
    measurementId: 'G-XDTV5NKW42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClfS158ah9cq_GY7qOAQNWfDn9utsG7Ss',
    appId: '1:214242900706:android:df81e58aa5e9b2fe4ffcbb',
    messagingSenderId: '214242900706',
    projectId: 'stand-app-fce12',
    storageBucket: 'stand-app-fce12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX6Yin4Cr2dQKoLe-zaPZpwi0e8ypYs7s',
    appId: '1:214242900706:ios:cb5ddc2ac20e0e9e4ffcbb',
    messagingSenderId: '214242900706',
    projectId: 'stand-app-fce12',
    storageBucket: 'stand-app-fce12.firebasestorage.app',
    iosBundleId: 'com.run.standapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX6Yin4Cr2dQKoLe-zaPZpwi0e8ypYs7s',
    appId: '1:214242900706:ios:63bda9c0cc2073994ffcbb',
    messagingSenderId: '214242900706',
    projectId: 'stand-app-fce12',
    storageBucket: 'stand-app-fce12.firebasestorage.app',
    iosBundleId: 'com.example.appGestionale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNBP3EfhLsnnz5OcQsPg2EpnQE19qvKG4',
    appId: '1:214242900706:web:212d0d091ff9c2f94ffcbb',
    messagingSenderId: '214242900706',
    projectId: 'stand-app-fce12',
    authDomain: 'stand-app-fce12.firebaseapp.com',
    storageBucket: 'stand-app-fce12.firebasestorage.app',
    measurementId: 'G-7CRGRJFKDM',
  );
}
